# Generated by Django 3.0.6 on 2020-05-21 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='users',
            new_name='user',
        ),
    ]
