# Generated by Django 3.0.6 on 2020-05-21 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200521_2146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
