# Generated by Django 3.0.6 on 2020-05-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0003_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=128, unique=True, verbose_name='用户名')),
                ('name', models.CharField(max_length=128, verbose_name='姓名')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女'), ('unknown', '不明')], default='男', max_length=32, verbose_name='性别')),
                ('phone', models.IntegerField(unique=True, verbose_name='电话号码')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '注册用户',
                'verbose_name_plural': '注册用户',
                'ordering': ['c_time'],
            },
        ),
    ]
