# Generated by Django 3.0.6 on 2020-05-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=40, unique=True, verbose_name='电话号码'),
        ),
    ]
