# Generated by Django 3.0.6 on 2020-05-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daydreamBkS', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '书籍', 'verbose_name_plural': '书籍'},
        ),
        migrations.AddField(
            model_name='book',
            name='badv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='bnum',
            field=models.IntegerField(default=1, verbose_name='库存数量'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='static/bimg/%Y/%m/%d/', verbose_name='书籍图片'),
        ),
    ]
