# Generated by Django 3.0.6 on 2020-05-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daydreamBkS', '0002_auto_20200521_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bclick',
            field=models.IntegerField(default=1, verbose_name='点击率'),
            preserve_default=False,
        ),
    ]
