# Generated by Django 3.0.6 on 2020-05-21 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daydreamBkS', '0005_auto_20200521_2127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
